### ISSUE TITLE
The symbol of the video is coming of like the youtube button.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Denny-Speed-App-Instal---Internal-16-June-#2]
**Actual result:**
The symbol of the button is not coming of like the youtube video.( In preview )
https://mamanaturesmosquitojuice.com/products/stop-the-swat-summer
**Expected result:**
The play button can be of youtube type.

**Comment by devabulabbas** [comment]
lazy load technique has been applied and new symbol has been added on thumbnail image
