### ISSUE TITLE
The debugger icon is coming

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Denny-Speed-App-Instal---Internal-16-June-#3]
**Actual result:**
The debugger icon is coming
![image](https://user-images.githubusercontent.com/102131636/173051775-da41ae61-c8c7-4470-a0fc-2dc78e04621b.png)

**Expected result:**
The debugger option can be closed ( Suggestion )

**Comment by devabulabbas** [comment]
This is comming Froma an app No Problem when anyone will open inspect elemnet only then this icon will come m
